accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

stressreduction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('about/', views.about),
    path('', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suggestions/urls.py
from django.urls import path

from . import views

app_name = "methods"

urlpatterns = [
    path('', views.suggestion_list, name="list"),
    path('recommend', views.give_recommendation, name="recommend"),
    path('<slug>', views.suggestion_detail, name="detail"),
    path('rate/', views.rate_image, name="rate")
]

accounts/models.py
# Create your models here.

suggestions/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


# from django.contrib.auth.models import User


class Method(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', default='default.png')
    description = models.TextField()
    score = models.IntegerField(default=0,
                                validators=[MaxValueValidator(5),
                                            MinValueValidator(0)
                                            ])
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)  # automatically populate field with the time suggestion was created.

    def __str__(self):
        # this function would enable us get the name in text when we call it from the shell programmatically
        return self.name

    def snippet(self):
        return self.description[:255] + "..."

    def str(self):
        return str(self.pk)

# class UserRating(models.Model):
# method = models.ForeignKey(Method, related_name='ratings', on_delete=models.CASCADE)
# user = models.ForeignKey(User, related_name='ratings', on_delete=models.CASCADE)

suggestions/forms.py
from django import forms

from . import models


class GetSelections(forms.ModelForm):
    class Meta:
        model = models.Method
        fields = ['name']
        """
        fields = ['height']
        fields = ['weight']
        fields = ['age']
        fields = ['occupation']
        fields = ['height']
        fields = ['name']
        fields = ['number of working hours']
        """

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('methods:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #  log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('methods:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("methods:list")

stressreduction/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage.html')


def about(request):
    return render(request, 'about.html')

suggestions/views.py
import pandas as pd
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render

from recommendations.recommender import get_similar_stress_reduction_method
from . import forms
# from django.http import HttpResponse
from .models import Method


def suggestion_list(request):
    # this grabs all of the records from this method database table
    methods = Method.objects.all().order_by('name')  # this orders the list by name
    return render(request, 'suggestions/suggestion_list.html', {"methods": methods})


@login_required(login_url="/accounts/login/")  # This prevents a user from accessing this page unless he has logged in
def suggestion_detail(request, slug):
    suggestion = Method.objects.get(slug=slug)
    return render(request, "suggestions/suggestion_detail.html", {"suggestion": suggestion})


@login_required(login_url="/accounts/login/")  # This prevents a user from accessing this page unless he has logged in
def give_recommendation(request):
    form = forms.GetSelections()
    selection_list = []

    def get_data(method_id, method_rating):
        selection_list.append((method_id, method_rating))
        return selection_list

    def recommendation(selections_list):
        similar_method = pd.DataFrame()
        for method, rating in selections_list:
            similar_method = similar_method.append(get_similar_stress_reduction_method(method, rating),
                                                   ignore_index=True)
        recommended = similar_method.sum().sort_values(ascending=False)
        return recommended

    # if it's a post request, pass the data as an argument into the get_data function to generate a selection list
    get_data('Yoga', 4)  # post data should go in here)
    get_data("laughter", 4)

    recommend = recommendation(selection_list)
    return render(request, 'suggestions/recommend.html', {"form": form, "recommend": recommend})


def rate_image(request):
    if request.method == 'POST':
        element_id = request.POST.get('element_id')
        val = request.POST.get('val')
        obj = Method.objects.get(id=element_id)
        obj.score = val
        obj.save()
        return JsonResponse({'success': 'true', 'score': val}, safe=False)
    return JsonResponse({'success': 'false'})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Log in</h1>
<form action="{% url 'accounts:login' %}" class="site-form" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input name="next" type="hidden" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
<form action="/accounts/signup/" class="site-form" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

suggestions/templates/suggestions/recommend.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="recommend-methods">
    <form action="" class="site-form" method="post">

    </form>

    {{ form }}
    {{ recommend }}
</div>
{% endblock %}

suggestions/templates/suggestions/suggestion_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="suggestion-detail">
    <div class="suggestion">
        <img alt="" src="{{ suggestion.thumb.url }}">
        <h2>{{ suggestion.name }}</h2>
        <p>{{ suggestion.description }}</p>
    </div>
</div>
{% endblock %}

suggestions/templates/suggestions/suggestion_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<h1>Suggestions To Help Reduce Stress</h1>
<div class="row">
    {% for method in methods %}
    <div class="col">
        <div class="card" style="width: 18rem;">
            <img alt="..." class="card-img-top" src="{{ method.image.url }}" width="50%">
            <div class="card-body">
                <h5 class="card-title">{{ method.name }}</h5>
                <p class="card-text">{{ method.snippet }}</p>
                <span class="heading">
                    How effective is this method for you?
                </span>
                <br>
                <form action="" class="rate-form" id="{{method.id}}" method="POST">
                    {% csrf_token %}
                    <button class="fa fa-star fa-2x star-btn" id="first" type="submit"></button>
                    <button class="fa fa-star fa-2x star-btn" id="second" type="submit"></button>
                    <button class="fa fa-star fa-2x star-btn" id="third" type="submit"></button>
                    <button class="fa fa-star fa-2x star-btn" id="fourth" type="submit"></button>
                    <button class="fa fa-star fa-2x star-btn" id="fifth" type="submit"></button>
                </form>
            </div>
            <br>
        </div>
    </div>
    {% endfor %}
    <a href="{% url 'methods:recommend' %}">
        <button class="btn btn-primary mt-3" id="recommend-box">Recommend</button>
</div>
{% endblock %}

suggestions/templates/suggestions/suggestion_list2.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Suggestions To Help Reduce Stress</h1>
<div class="methods">
    {% for method in methods %}
    <div class="method">
        <h2>{{ method.name }}</h2>
        <h2>{{ method.thumb }}</h2>
        <p>{{ method.snippet }}</p>
        # rating here
        <p><a href="{% url 'methods:detail' slug=method.slug %}">
            <button type="button">Read More</button>
        </a></p>
    </div>
    {% endfor %}
    <p><a href="{% url 'methods:recommend' %}">
        <input type="submit" value="Recommend">
</div>
{% endblock %}

suggestions/templates/suggestions/test.html
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
<span class="fa fa-star"></span>

<link href="{% static 'style.css' %}" rel="stylesheet">
<script defer src="{% static 'main.js' %}"></script>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"></script>

methods:recommend

<span class="fa fa-star checked" onclick="onClickStar('1','1')"></span>
<span class="fa fa-star checked" onclick="onClickStar('1','2')"></span>
<span class="fa fa-star checked" onclick="onClickStar('1','3')"></span>
<span class="fa fa-star checked" onclick="onClickStar('1','4')"></span>
<span class="fa fa-star" onclick="onClickStar('1','5')"></span>
<link href="{% static 'star-ratings/css/star-ratings.css' %}" rel="stylesheet">
<script src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}" type="text/javascript"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
        function onClickStar(id,starid){
        console.log(id,starid)
        param = id
        $.ajax(
        {
        type: "POST",
        url:
        data: param

        }
        )
        }

templates/about.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>About</title>
</head>
<body>
<h1>About us</h1>
<p>We like helping you relieve stress</p>
</body>
</html>

templates/base_layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- jquery -->
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" rel="stylesheet">

    <!-- Font awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- custom css & js -->
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <script defer src="{% static 'main.js' %}"></script>


    <title>List of Stress Reduction Methods</title>
</head>
<body>
<header class="wrapper">
    <h1><a href="{% url 'methods:list' %}"><img alt="" src="{% static 'img.jpg' %}"></a></h1>
    <nav>
        <ul>
            <li>
                <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        </ul>
    </nav>
</header>
<!-- As a link -->
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'methods:list' %}">Stress Reduction Methods</a>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/base_layout2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Suggestions</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
<header class="wrapper">
    <h1><a href="{% url 'methods:list' %}"><img alt="" src="{% static 'img.jpg' %}"></a></h1>
    <nav>
        <ul>
            <li>
                <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        </ul>
    </nav>
</header>
<div class="wrapper">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Homepage</title>
</head>
<body>
<h1>This is the homepage</h1>
<p>Welcome to the number one stress reduction website</p>
</body>
</html>